notifications:
  email: false

branches:
  only:
    - master
    - develop
    - /^v\d+\.\d+\.\d+/

language: node_js

node_js:
  - '10'
  - '12'

install:
  - yarn install --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: Check TypeScript
      script:
        - yarn check:types
    - stage: Lint
      script:
        - yarn lint
    - stage: Check Formatting
      script:
        - yarn check:format
    - stage: Test
      script:
        - yarn test
    - stage: Build
      script:
        - yarn build
