dist: trusty
language: node_js
notifications:
  email:
    on_success: change
    on_failure: always

cache: yarn

jobs:
  include:
    - stage: Test
      name: Lint
      node_js: 10
      script:
        - yarn run lint
    - stage: Test
      name: Formatting
      node_js: 10
      script:
        - yarn run check-formatting
    - stage: Test
      name: Jest (node:8)
      node_js: 8
      if: branch = master or type =  pull_request
      script:
        - yarn run test --coverage
    - stage: Test
      name: Jest (node:10)
      node_js: 10
      script:
        - yarn run test --coverage
        - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"
    - stage: Build
      name: Build (node:8)
      node_js: 8
      if: branch = master or type =  pull_request
      script:
        - yarn run build
    - stage: Build
      name: Build (node:10)
      node_js: 10
      script:
        - yarn run build
        # - yarn run bundlesize
    - stage: E2E
      name: Subscription Example
      node_js: 10
      # if: branch = master or type =  pull_request
      script:
        - cd examples/2-using-subscriptions
        - yarn
        - yarn start &
        - yarn run e2e
