blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/urql-graphql/urql/discussions
    about: Ask questions and discuss with other community members
  - name: Join the Discord
    url: https://urql.dev/discord
    about: Chat with maintainers and other community members
